apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-validation-webhook
  template:
    metadata:
      labels:
        app: resource-validation-webhook
      annotations:
        microserviceName: "XYZ"
        microserviceSize: "L"
    spec:
      containers:
      - name: webapp1
        image: nginx
        resources:
          requests:
            cpu: "1"
            memory: "100Mi"