apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-validation-webhook
  labels:
    app: resource-validation-webhook
spec:
  template:
    spec:
      containers:
      - name: server
        image: pkulkarni4/admission-webhook:v5
        imagePullPolicy: Never